### ISSUE TITLE
I have a problem with the 'Lato' font, I get text wrap

### ISSUE THREAD

**Issue by cinzianicoletti** [snm-miek/MKitFPdf#1]
The plugin is excellent, but with the font 'Lato' some (not all) texts wrap, I will forward you some screenshots.

I also notice that a frame is created around the pdf which does not exist in reality.
The font size is also not respected.

Thank you very much
<img width="436" alt="Screenshot 2023-12-07 alle 14 31 46" src="https://github.com/snm-miek/MKitFPdf/assets/9805969/c0bc2966-8cee-40f9-a667-8a9c8afc7a35">

**Comment by clarah31** [comment]
I need a Figma example file or a link to the Figma file.

**Comment by snm-miek** [comment]
Thank you for reporting the problem.
It has been fixed in version v1.16 from 11.1.2024.
