### ISSUE TITLE
Image are upside down in the export

### ISSUE THREAD

**Issue by antoineov** [snm-miek/MKitFPdf#2]
When I do an export all my images are upside down and in poor quality

**Comment by clarah31** [comment]
I am only aware of this problem with the macos/ios preview, it should work in Adobe Reader.
If it also happens in Adobe Reader, then I need a Figma file or URL with the problem.

Otherwise, I am waiting for the release of the new version of FIGMA
(fix preview flipped images)

**Comment by antoineov** [comment]
Ah yes it's working in adobe Reader, okay a bit weird but I'll wait the release

**Comment by snm-miek** [comment]
Thank you for reporting the problem.
It has been fixed in version v1.16 from 11.1.2024.
