### ISSUE TITLE
Bullet Spacing and text 

### ISSUE THREAD

**Issue by 10eputzen** [snm-miek/MKitFPdf#3]
I really like the tool, but I still get a couple of formating issues.

The bullet spacing is off:
![image](https://github.com/snm-miek/MKitFPdf/assets/11854929/620365dd-b43b-40cd-a37b-a426eccc9dbb)

![image](https://github.com/snm-miek/MKitFPdf/assets/11854929/91e410ac-b19b-4726-bcb0-f719d39cd492)

And the text underline stops a couple of pixels before the end
![image](https://github.com/snm-miek/MKitFPdf/assets/11854929/6c2587d6-4025-42b8-8586-f81778d575ae)

![image](https://github.com/snm-miek/MKitFPdf/assets/11854929/6b5fbb31-a43e-4afc-b8f4-fecf6c83242d)

Figma Link: https://www.figma.com/file/c8duhZNZL6XSZTfzTMpmvW/MKitFPdf-Issue?type=design&node-id=0%3A1&mode=design&t=kdlQcWAlM3Azbjyo-1

**Comment by snm-miek** [comment]
Thank you for reporting the problem.
It has been fixed in version v1.16 from 11.1.2024.
